apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data:
  CART_HOST: "{{ .Values.payment.configmap.CART_HOST }}"
  CART_PORT: "{{ .Values.payment.configmap.CART_PORT }}"
  USER_HOST: "{{ .Values.payment.configmap.USER_HOST }}"
  USER_PORT: "{{ .Values.payment.configmap.USER_PORT }}"
  AMQP_HOST: "{{ .Values.payment.configmap.AMQP_HOST }}"
  AMQP_USER: "{{ .Values.payment.configmap.AMQP_USER }}"
  AMQP_PASS: "{{ .Values.payment.configmap.AMQP_PASS }}"