apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: roboshop
data:
  RABBITMQ_DEFAULT_USER: "{{ .Values.rabbitmq.configmap.RABBITMQ_DEFAULT_USER }}"
  RABBITMQ_DEFAULT_PASS: "{{ .Values.rabbitmq.configmap.RABBITMQ_DEFAULT_PASS }}"