apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: catalogue
  replicas: {{ .Values.catalogue.deployment.replicas }}
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: catalogue   
    spec:
      containers:
        - name: catalogue
          image: {{ .Values.catalogue.image.repository }}:{{ .Values.catalogue.image.tag }} #saithota9/catalogue:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "55m"
              memory: "40Mi"
            limits:
              cpu: "100m"
              memory: "170Mi"
          readinessProbe:
            # httpGet:
            #   path: /health
            #   port: 8080
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            # httpGet:
            #   path: /health
            #   port: 8080
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: catalogue
      affinity:
         nodeAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             nodeSelectorTerms:
               - matchExpressions:
                   - key: tier
                     operator: In
                     values:
                       - backend